export { default as Login } from './Login'
export { default as Main } from './Main'
export { default as MyHeader } from './MyHeader'
export { default as MySidebar } from './MySidebar'
export { default as PageLoading } from './PageLoading'
export { default as Register } from './Register'
export { default as Forgot } from './Forgot'
export { default as Reset } from './Reset'
